### ISSUE TITLE
Worker process randomly dies during MOSMIX parsing

### ISSUE THREAD

**Issue by smilingchemist** [jdemaeyer/brightsky#130] opened 2022-08-01 12:04 UTC
Hi, thanks for providing this great API!

I have been trying around for some days now but I think there is an issue. During the past 48 hours (approx.) the field "last_record" shows "2022-08-08T16:00:00+00:00" in the forecast sources. Is there maybe a problem with updating the forecasts or is this normal behaviour?

Thank you in advance!

**Comment by jdemaeyer** [comment] 2022-08-01 14:25
Hi @smilingchemist,

thanks for the report, I must've falsely judged a Sentry notification as "one-time error" there. Seems that restarting our worker fixed it for now, I'll look into the cause once I'm back from vacation.

Cheers,
-Jakob

**Comment by smilingchemist** [comment] 2022-08-01 19:31
Hi Jakob,

I fear the issue came back. I wish you a nice holiday anyway.

Frank

**Comment by jdemaeyer** [comment] 2022-08-11 10:20
Digging through the Sentry issue suggests that this is based on worker processes breaking while processing `MOSMIX` files. Maybe it's some memory issue (although we do have plenty of free memory). I will try playing around with the number of `huey` workers and/or their type, although this is more wild guessing than actually knowing what's going on.

**Comment by jdemaeyer** [comment] 2022-08-11 13:19
4f02502

**Comment by jdemaeyer** [comment] 2023-06-21 08:56
Closing as this hasn't happened in forever. The memory footprint during parsing was greatly reduced when we refactored to use [`dwdparse`](https://github.com/jdemaeyer/dwdparse).

**Closed by jdemaeyer** 2023-06-21 08:56 UTC
